//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface ArticleResponse {
    id?: number;
    cityId?: number;
    headline?: string | undefined;
    summary?: string | undefined;
    sourceName?: string | undefined;
    sourceUrl?: string | undefined;
    publishedAt?: string;
    category?: string | undefined;
    imageUrl?: string | undefined;
}

export interface CityResponse {
    id?: number;
    name?: string | undefined;
    state?: string | undefined;
    slug?: string | undefined;
}

export interface HealthResponse {
    status?: string | undefined;
    service?: string | undefined;
    timestampUtc?: string;
    database?: string | undefined;
}

export interface IngestRunResponse {
    feedsAttempted?: number;
    feedsFailed?: number;
    inserted?: number;
    skipped?: number;
}

export interface PagedArticlesResponse {
    items?: ArticleResponse[] | undefined;
    total?: number;
    offset?: number;
    limit?: number;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}