//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AdminArticleResponse {
    id?: number;
    cityId?: number;
    headline?: string | undefined;
    summary?: string | undefined;
    sourceName?: string | undefined;
    sourceUrl?: string | undefined;
    publishedAt?: string;
    category?: string | undefined;
    imageUrl?: string | undefined;
    status?: ArticleStatus;
    isMock?: boolean;
    ingestedAt?: string | undefined;
    reviewedBy?: string | undefined;
    reviewedAt?: string | undefined;
    sourceId?: number | undefined;
}

export interface AdminLoginRequest {
    password?: string | undefined;
    displayName?: string | undefined;
}

export interface AdminLoginResponse {
    token?: string | undefined;
    expiresAt?: string;
}

export interface AdminSourceResponse {
    id?: number;
    name?: string | undefined;
    feedUrl?: string | undefined;
    cityId?: number;
    citySlug?: string | undefined;
    type?: SourceType;
    kind?: SourceKind;
    language?: string | undefined;
    isActive?: boolean;
    lastFetchedAt?: string | undefined;
    lastFetchStatus?: FetchStatus;
    lastErrorMessage?: string | undefined;
}

export interface ArticleResponse {
    id?: number;
    cityId?: number;
    headline?: string | undefined;
    summary?: string | undefined;
    sourceName?: string | undefined;
    sourceUrl?: string | undefined;
    publishedAt?: string;
    category?: string | undefined;
    imageUrl?: string | undefined;
}

export enum ArticleStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

export interface CityResponse {
    id?: number;
    name?: string | undefined;
    state?: string | undefined;
    slug?: string | undefined;
}

export interface CreateAdminArticleRequest {
    headline?: string | undefined;
    summary?: string | undefined;
    city?: string | undefined;
    category?: string | undefined;
    sourceName?: string | undefined;
    sourceUrl?: string | undefined;
    publishNow?: boolean;
}

export interface CreateAdminSourceRequest {
    name?: string | undefined;
    feedUrl?: string | undefined;
    city?: string | undefined;
    type?: SourceType;
    kind?: SourceKind;
    language?: string | undefined;
    isActive?: boolean;
}

export enum FetchStatus {
    _0 = 0,
    _1 = 1,
}

export interface HealthResponse {
    status?: string | undefined;
    service?: string | undefined;
    timestampUtc?: string;
    database?: string | undefined;
}

export interface IngestRunResponse {
    feedsAttempted?: number;
    feedsFailed?: number;
    inserted?: number;
    skipped?: number;
}

export interface IngestionRunResponseDto {
    id?: number;
    sourceId?: number;
    startedAt?: string;
    completedAt?: string | undefined;
    articlesFound?: number;
    articlesAdded?: number;
    articlesSkipped?: number;
    articlesFailed?: number;
    errorSummary?: string | undefined;
}

export interface PagedAdminArticlesResponse {
    items?: AdminArticleResponse[] | undefined;
    total?: number;
    page?: number;
    limit?: number;
}

export interface PagedArticlesResponse {
    items?: ArticleResponse[] | undefined;
    total?: number;
    offset?: number;
    limit?: number;
}

export interface PagedIngestionRunsResponse {
    items?: IngestionRunResponseDto[] | undefined;
    total?: number;
    page?: number;
    limit?: number;
}

export interface PatchAdminArticleRequest {
    headline?: string | undefined;
    summary?: string | undefined;
    category?: string | undefined;
    city?: string | undefined;
}

export interface PatchAdminSourceRequest {
    name?: string | undefined;
    feedUrl?: string | undefined;
    city?: string | undefined;
    type?: SourceType;
    kind?: SourceKind;
    language?: string | undefined;
    isActive?: boolean | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export enum SourceKind {
    _0 = 0,
    _1 = 1,
}

export enum SourceType {
    _0 = 0,
    _1 = 1,
}