// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsFeed.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsFeed.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803083338_AddCitiesAndArticles")]
    partial class AddCitiesAndArticles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsFeed.Api.Data.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("headline");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "PublishedAt");

                    b.ToTable("articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Local",
                            CityId = 2,
                            Headline = "[MOCK] Local municipal budget approved for FY26",
                            ImageUrl = "https://picsum.photos/seed/jhansi1/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Dainik Jagran",
                            SourceUrl = "https://example.com/mock/1",
                            Summary = "The Jhansi Municipal Corporation cleared the annual budget in a special session. Funds prioritize water supply repairs and street lighting in older wards."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Local",
                            CityId = 2,
                            Headline = "[MOCK] झांसी में गर्मी से राहत के लिए जल केंद्र खुले",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 3, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Amar Ujala",
                            SourceUrl = "https://example.com/mock/2",
                            Summary = "नगर निगम ने मुख्य चौराहों पर अस्थायी जल वितरण केंद्र शुरू किए। स्वयंसेवक सुबह और शाम पाली में ड्यूटी पर हैं।"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Health",
                            CityId = 2,
                            Headline = "[MOCK] District hospital expands OPD hours for seniors",
                            ImageUrl = "https://picsum.photos/seed/jhansi2/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Hindustan",
                            SourceUrl = "https://example.com/mock/3",
                            Summary = "New evening OPD slots aim to cut wait times for patients over 60. Officials say walk-in registration will open at 4 pm on weekdays."
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sports",
                            CityId = 2,
                            Headline = "[MOCK] Inter-college cricket final draws packed stands",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/4",
                            Summary = "Rani Lakshmibai College beat City College by 42 runs in the district final. Organizers thanked volunteers for crowd management."
                        },
                        new
                        {
                            Id = 5,
                            Category = "Business",
                            CityId = 2,
                            Headline = "[MOCK] Small traders seek GST help desk at market",
                            ImageUrl = "https://picsum.photos/seed/jhansi3/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/5",
                            Summary = "Cloth market association asked for a weekly help desk for filing queries. The commercial tax office said a pilot desk may start next month."
                        },
                        new
                        {
                            Id = 6,
                            Category = "State",
                            CityId = 2,
                            Headline = "[MOCK] State road works pause near Orchha junction",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "UP News Desk Mock",
                            SourceUrl = "https://example.com/mock/6",
                            Summary = "PWD paused overnight resurfacing after monsoon forecasts. Diversions remain in place for heavy vehicles through the weekend."
                        },
                        new
                        {
                            Id = 7,
                            Category = "Health",
                            CityId = 2,
                            Headline = "[MOCK] Free eye camp scheduled at community hall",
                            ImageUrl = "https://picsum.photos/seed/jhansi4/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Health Today Mock",
                            SourceUrl = "https://example.com/mock/7",
                            Summary = "Local NGO and district health team will screen cataracts this Sunday. Appointments are not required; bring an ID card if available."
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sports",
                            CityId = 2,
                            Headline = "[MOCK] Women runners finish charity 5K in Bundelkhand heat",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/8",
                            Summary = "Over 200 participants completed the morning route from the fort gate. Proceeds go to a neighborhood literacy fund."
                        },
                        new
                        {
                            Id = 9,
                            Category = "Business",
                            CityId = 2,
                            Headline = "[MOCK] Co-operative bank opens new KCC window",
                            ImageUrl = "https://picsum.photos/seed/jhansi5/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/9",
                            Summary = "Farmers can apply for Kisan Credit Card renewals without prior appointment this fortnight. Branch hours extend to 6 pm on Fridays."
                        },
                        new
                        {
                            Id = 10,
                            Category = "State",
                            CityId = 2,
                            Headline = "[MOCK] Power department clears monsoon contingency plan",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "UP News Desk Mock",
                            SourceUrl = "https://example.com/mock/10",
                            Summary = "Emergency crews and spare transformers are staged for Bundelkhand districts. Hotline numbers will be published on ward notice boards."
                        },
                        new
                        {
                            Id = 11,
                            Category = "Business",
                            CityId = 3,
                            Headline = "[MOCK] Leather cluster workshop on export compliance",
                            ImageUrl = "https://picsum.photos/seed/kanpur1/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/11",
                            Summary = "Industry body hosted a half-day session on documentation for small exporters. Speakers stressed early GST reconciliation before shipments."
                        },
                        new
                        {
                            Id = 12,
                            Category = "Local",
                            CityId = 3,
                            Headline = "[MOCK] कानपुर में नदी किनारे सफाई अभियान",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Dainik Jagran",
                            SourceUrl = "https://example.com/mock/12",
                            Summary = "स्थानीय युवा समूह ने घाट क्षेत्र की सफाई की। नगर निगम ने अतिरिक्त कचरा वाहन उपलब्ध कराए।"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Sports",
                            CityId = 3,
                            Headline = "[MOCK] City marathon route announced for October",
                            ImageUrl = "https://picsum.photos/seed/kanpur2/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/13",
                            Summary = "The 10K loop will avoid peak market streets before 8 am. Registration opens online next week with senior citizen discounts."
                        },
                        new
                        {
                            Id = 14,
                            Category = "Health",
                            CityId = 3,
                            Headline = "[MOCK] Dengue awareness drive in schools",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Hindustan",
                            SourceUrl = "https://example.com/mock/14",
                            Summary = "Health workers demonstrated larvicide use and home checks. Parents received printed checklists in Hindi and English."
                        },
                        new
                        {
                            Id = 15,
                            Category = "State",
                            CityId = 3,
                            Headline = "[MOCK] State bus depot adds evening Lucknow services",
                            ImageUrl = "https://picsum.photos/seed/kanpur3/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "UP News Desk Mock",
                            SourceUrl = "https://example.com/mock/15",
                            Summary = "Two extra AC buses will run after 7 pm on weekdays. Tickets can be booked at the counter or via the state portal."
                        },
                        new
                        {
                            Id = 16,
                            Category = "Local",
                            CityId = 3,
                            Headline = "[MOCK] Neighborhood library extends weekend hours",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 4, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Amar Ujala",
                            SourceUrl = "https://example.com/mock/16",
                            Summary = "Reading room stays open until 8 pm on Saturdays. Volunteers will help first-time users find newspapers and magazines."
                        },
                        new
                        {
                            Id = 17,
                            Category = "Health",
                            CityId = 3,
                            Headline = "[MOCK] Blood donation camp at engineering campus",
                            ImageUrl = "https://picsum.photos/seed/kanpur4/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Health Today Mock",
                            SourceUrl = "https://example.com/mock/17",
                            Summary = "District blood bank partnered with student clubs for a one-day drive. Walk-ins welcome after a brief health screening."
                        },
                        new
                        {
                            Id = 18,
                            Category = "Sports",
                            CityId = 3,
                            Headline = "[MOCK] Local football league resumes under lights",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/18",
                            Summary = "Floodlit matches return after pitch repairs. Season fixtures will be posted at the municipal sports office."
                        },
                        new
                        {
                            Id = 19,
                            Category = "Business",
                            CityId = 3,
                            Headline = "[MOCK] MSME help desk clarifies invoice financing",
                            ImageUrl = "https://picsum.photos/seed/kanpur5/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/19",
                            Summary = "Bankers answered questions on working-capital products for workshops. Follow-up clinics are planned monthly."
                        },
                        new
                        {
                            Id = 20,
                            Category = "Local",
                            CityId = 4,
                            Headline = "[MOCK] Gomti riverside walkway lighting upgraded",
                            ImageUrl = "https://picsum.photos/seed/lucknow1/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Dainik Jagran",
                            SourceUrl = "https://example.com/mock/20",
                            Summary = "New LED fixtures cover the popular evening stretch. Civic teams asked residents to report dark spots via the ward app."
                        },
                        new
                        {
                            Id = 21,
                            Category = "State",
                            CityId = 4,
                            Headline = "[MOCK] State capital hosts digital literacy fair",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 4, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "UP News Desk Mock",
                            SourceUrl = "https://example.com/mock/21",
                            Summary = "Seniors practiced video calls and UPI basics at free booths. Sessions run through the weekend at the exhibition ground."
                        },
                        new
                        {
                            Id = 22,
                            Category = "Sports",
                            CityId = 4,
                            Headline = "[MOCK] Lucknow Super Giants fan zone mock preview",
                            ImageUrl = "https://picsum.photos/seed/lucknow2/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/22",
                            Summary = "A temporary fan zone mock setup tested crowd flow near the stadium. Organizers say real match-day plans will differ."
                        },
                        new
                        {
                            Id = 23,
                            Category = "Health",
                            CityId = 4,
                            Headline = "[MOCK] Polyclinic adds physiotherapy slots",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Hindustan",
                            SourceUrl = "https://example.com/mock/23",
                            Summary = "Morning physiotherapy appointments open for joint pain cases. Doctors advise early booking for monsoon-related flare-ups."
                        },
                        new
                        {
                            Id = 24,
                            Category = "Local",
                            CityId = 4,
                            Headline = "[MOCK] Handloom exhibition draws weekend crowds",
                            ImageUrl = "https://picsum.photos/seed/lucknow3/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Amar Ujala",
                            SourceUrl = "https://example.com/mock/24",
                            Summary = "Artisans from nearby districts displayed chikankari and cotton weaves. Organizers capped entry to keep aisles walkable."
                        },
                        new
                        {
                            Id = 25,
                            Category = "Business",
                            CityId = 4,
                            Headline = "[MOCK] Startup clinic explains FSSAI basics for cafes",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 5, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/25",
                            Summary = "Food entrepreneurs attended a free morning clinic. Mentors walked through labeling and kitchen checklist requirements."
                        },
                        new
                        {
                            Id = 26,
                            Category = "Health",
                            CityId = 4,
                            Headline = "[MOCK] Heat advisory tips shared for outdoor workers",
                            ImageUrl = "https://picsum.photos/seed/lucknow4/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Health Today Mock",
                            SourceUrl = "https://example.com/mock/26",
                            Summary = "Health department posted rest-and-water guidance for construction crews. NGOs will distribute ORS packets at major sites."
                        },
                        new
                        {
                            Id = 27,
                            Category = "Sports",
                            CityId = 4,
                            Headline = "[MOCK] Inter-school kho-kho finals this Saturday",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/27",
                            Summary = "Eight teams remain in the city championship. Matches begin at 7 am at the university ground."
                        },
                        new
                        {
                            Id = 28,
                            Category = "State",
                            CityId = 4,
                            Headline = "[MOCK] State tourism office posts monsoon itineraries",
                            ImageUrl = "https://picsum.photos/seed/lucknow5/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "UP News Desk Mock",
                            SourceUrl = "https://example.com/mock/28",
                            Summary = "Suggested day trips highlight museums and indoor heritage sites. Officials caution against unverified riverside picnic spots."
                        },
                        new
                        {
                            Id = 29,
                            Category = "Local",
                            CityId = 1,
                            Headline = "[MOCK] Taj periphery traffic trial for weekends",
                            ImageUrl = "https://picsum.photos/seed/agra1/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Dainik Jagran",
                            SourceUrl = "https://example.com/mock/29",
                            Summary = "Police will test one-way loops near popular photo points. Signage goes up Friday evening; feedback desks at two junctions."
                        },
                        new
                        {
                            Id = 30,
                            Category = "Local",
                            CityId = 1,
                            Headline = "[MOCK] आगरा में पेयजल पाइपलाइन मरम्मत",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 8, 1, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Amar Ujala",
                            SourceUrl = "https://example.com/mock/30",
                            Summary = "जल संस्थान की टीम ने पुरानी लाइन बदलने का काम शुरू किया। प्रभावित कॉलोनियों में टैंकर सेवा अस्थायी रूप से बढ़ाई गई।"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Health",
                            CityId = 1,
                            Headline = "[MOCK] Heritage walk guides complete first aid course",
                            ImageUrl = "https://picsum.photos/seed/agra2/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Health Today Mock",
                            SourceUrl = "https://example.com/mock/31",
                            Summary = "Tour guides finished a weekend module on heat illness and crowd injuries. Certificates were issued by a local Red Cross unit."
                        },
                        new
                        {
                            Id = 32,
                            Category = "Sports",
                            CityId = 1,
                            Headline = "[MOCK] District athletics meet sets school records",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/32",
                            Summary = "Two under-16 runners broke long-standing 100m marks. Coaches credited early-morning practice in cooler weather."
                        },
                        new
                        {
                            Id = 33,
                            Category = "Business",
                            CityId = 1,
                            Headline = "[MOCK] Leather and footwear stalls at trade fair",
                            ImageUrl = "https://picsum.photos/seed/agra3/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/33",
                            Summary = "Local makers showed sample batches for domestic buyers. A help desk explained packaging standards for online sellers."
                        },
                        new
                        {
                            Id = 34,
                            Category = "State",
                            CityId = 1,
                            Headline = "[MOCK] State archaeology office lists monsoon closures",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "UP News Desk Mock",
                            SourceUrl = "https://example.com/mock/34",
                            Summary = "Some outdoor monument sections may close during heavy rain. Visitors should check the notice board before climbing steps."
                        },
                        new
                        {
                            Id = 35,
                            Category = "Health",
                            CityId = 1,
                            Headline = "[MOCK] Free BP check camp near civil lines",
                            ImageUrl = "https://picsum.photos/seed/agra4/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 31, 1, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Hindustan",
                            SourceUrl = "https://example.com/mock/35",
                            Summary = "Pharmacists and ASHA workers will screen adults on Sunday morning. Results cards include diet tips in simple Hindi."
                        },
                        new
                        {
                            Id = 36,
                            Category = "Sports",
                            CityId = 1,
                            Headline = "[MOCK] Night cricket nets reopen at club ground",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Sports Express Mock",
                            SourceUrl = "https://example.com/mock/36",
                            Summary = "Floodlights are back after wiring repairs. Members can book 45-minute slots via the club notice board."
                        },
                        new
                        {
                            Id = 37,
                            Category = "Business",
                            CityId = 1,
                            Headline = "[MOCK] Hotel association briefs staff on guest safety drills",
                            ImageUrl = "https://picsum.photos/seed/agra5/640/360",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 7, 30, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceName = "Business Line Mock",
                            SourceUrl = "https://example.com/mock/37",
                            Summary = "Managers reviewed evacuation and first-response steps. A city fire officer answered questions after the presentation."
                        });
                });

            modelBuilder.Entity("NewsFeed.Api.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Agra",
                            Slug = "agra",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jhansi",
                            Slug = "jhansi",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kanpur",
                            Slug = "kanpur",
                            State = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lucknow",
                            Slug = "lucknow",
                            State = "Uttar Pradesh"
                        });
                });

            modelBuilder.Entity("NewsFeed.Api.Data.Entities.Article", b =>
                {
                    b.HasOne("NewsFeed.Api.Data.Entities.City", "City")
                        .WithMany("Articles")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("NewsFeed.Api.Data.Entities.City", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
